// ---------------------------------------------------------------------------
// Catálogo de productos de SebasPeru.
// `image` es una clave que se resuelve a un componente SVG en imageMap.jsx,
// manteniendo los datos serializables (útil para SEO / sitemap / pruebas).
// ---------------------------------------------------------------------------

export const categories = [
  {
    slug: 'laptops-pc', name: 'Laptops & PC', image: 'laptop',
    subcategories: [
      { slug: 'laptops', name: 'Laptops' },
      { slug: 'laptops-gamer', name: 'Laptops Gamer' },
      { slug: 'ultrabooks', name: 'Ultrabooks' },
      { slug: 'convertibles', name: '2 en 1 / Convertibles' },
      { slug: 'monitores', name: 'Monitores' },
    ],
  },
  {
    slug: 'impresoras', name: 'Impresoras', image: 'printer',
    subcategories: [
      { slug: 'multifuncionales', name: 'Multifuncionales' },
      { slug: 'laser', name: 'Láser' },
      { slug: 'tinta-continua', name: 'Tinta continua' },
    ],
  },
  {
    slug: 'toner', name: 'Tóner', image: 'toner',
    subcategories: [
      { slug: 'toner-hp', name: 'Tóner HP' },
      { slug: 'toner-brother', name: 'Tóner Brother' },
    ],
  },
  {
    slug: 'tintas', name: 'Tintas', image: 'ink',
    subcategories: [
      { slug: 'tinta-epson', name: 'Tinta Epson' },
      { slug: 'tinta-canon', name: 'Tinta Canon' },
    ],
  },
  {
    slug: 'redes', name: 'Redes', image: 'router',
    subcategories: [
      { slug: 'routers', name: 'Routers' },
      { slug: 'switches', name: 'Switches' },
      { slug: 'access-points', name: 'Access Points' },
    ],
  },
  {
    slug: 'accesorios', name: 'Accesorios', image: 'headset',
    subcategories: [
      { slug: 'audifonos', name: 'Audífonos' },
      { slug: 'teclados-mouse', name: 'Teclados y Mouse' },
    ],
  },
  {
    slug: 'oficina', name: 'Oficina', image: 'chair',
    subcategories: [
      { slug: 'sillas', name: 'Sillas' },
      { slug: 'escritorios', name: 'Escritorios' },
    ],
  },
]

export const brands = ['HP', 'Lenovo', 'Dell', 'ASUS', 'Acer', 'Epson', 'Canon', 'Brother', 'Samsung', 'Logitech', 'TP-Link']

export const products = [
  {
    id: 1, sku: 'HP-250G9-I5', slug: 'laptop-hp-250-g9',
    name: 'Laptop HP 250 G9', brand: 'HP', model: '250 G9',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 1899, oldPrice: 2199, off: 16, stock: 8, rating: 4.8, reviews: 124, offer: true,
    subtitle: '15.6" FHD | 8GB | 512GB SSD',
    blurb: 'Intel Core i5 · 8GB RAM · 512GB SSD · 15.6" FHD · Windows 11',
    trendTag: '#Laptops', rankLabel: '#1 Más vendidos en Laptops HP',
    shortDesc: 'Laptop HP 250 G9 con procesador Intel Core i5, 8GB RAM y 512GB SSD. Ideal para trabajo, estudios y uso diario.',
    longDesc: 'La Laptop HP 250 G9 combina rendimiento y portabilidad en un diseño elegante y resistente. Perfecta para profesionales y estudiantes que necesitan productividad y confiabilidad en su día a día.',
    highlights: ['Rendimiento confiable para multitarea', 'Almacenamiento SSD para mayor velocidad', 'Diseño delgado y ligero', 'Batería de larga duración'],
    specs: { Procesador: 'Intel Core i5-1135G7 (11va Gen)', 'Memoria RAM': '8GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" HD (1366 x 768)', 'Sistema Operativo': 'Windows 11 Home', Peso: '1.74 kg', Garantía: '1 año' },
    compatibilities: [], related: [16, 17, 18, 19, 20],
  },
  {
    id: 2, sku: 'EP-L3250', slug: 'impresora-epson-l3250',
    name: 'Impresora Epson L3250 Multifuncional', brand: 'Epson', model: 'L3250',
    category: 'impresoras', subcategory: 'tinta-continua', image: 'printer',
    price: 699, stock: 15, rating: 4.7, reviews: 98, offer: false,
    shortDesc: 'Multifuncional Epson EcoTank L3250 con sistema de tinta continua, WiFi e impresión móvil.',
    longDesc: 'La Epson EcoTank L3250 es una impresora multifuncional inalámbrica con sistema de tanque de tinta de alta capacidad que reduce drásticamente el costo por página. Imprime, escanea y copia con calidad profesional, y se conecta vía WiFi para imprimir desde tu smartphone con Epson Smart Panel.',
    specs: { Tipo: 'Multifuncional tinta continua', Conectividad: 'WiFi, USB', Funciones: 'Imprime / Escanea / Copia', 'Velocidad': '33 ppm negro', Garantía: '1 año' },
    compatibilities: ['Tinta Epson 664'], related: [4, 11, 1],
  },
  {
    id: 3, sku: 'HP-CE285A-85A', slug: 'toner-hp-85a-ce285a',
    name: 'Tóner HP 85A CE285A Negro Original', brand: 'HP', model: '85A CE285A',
    category: 'toner', subcategory: 'toner-hp', image: 'toner',
    price: 59, stock: 40, rating: 4.8, reviews: 124, offer: false,
    shortDesc: 'Cartucho de tóner HP 85A (CE285A) negro original, rendimiento 1600 páginas.',
    longDesc: 'El cartucho de tóner original HP 85A (CE285A) garantiza impresiones nítidas y consistentes página tras página. Diseñado para integrarse perfectamente con tu impresora HP LaserJet, ofrece un rendimiento aproximado de 1600 páginas y la confiabilidad de un consumible original.',
    specs: { Color: 'Negro', Rendimiento: '~1600 páginas', Tipo: 'Original', Garantía: '1 año' },
    compatibilities: ['HP LaserJet P1102', 'HP LaserJet M1132', 'HP LaserJet M1212nf'], related: [11, 2, 4],
  },
  {
    id: 4, sku: 'EP-664-BK', slug: 'tinta-epson-664-negro',
    name: 'Tinta Epson 664 Negro Original', brand: 'Epson', model: '664',
    category: 'tintas', subcategory: 'tinta-epson', image: 'ink',
    price: 39, stock: 60, rating: 4.9, reviews: 256, offer: false,
    shortDesc: 'Botella de tinta Epson 664 negro original de 70ml para impresoras EcoTank.',
    longDesc: 'La tinta original Epson 664 negra de 70ml está formulada para ofrecer resultados de impresión nítidos y duraderos en tu impresora EcoTank. Su práctico sistema de llenado evita derrames y garantiza un rendimiento óptimo a un costo por página excepcionalmente bajo.',
    specs: { Color: 'Negro', Contenido: '70 ml', Tipo: 'Original', Garantía: '6 meses' },
    compatibilities: ['Epson L3250', 'Epson L3210', 'Epson L1210', 'Epson L5290'], related: [2, 3, 11],
  },
  {
    id: 5, sku: 'TPL-ARCHERC6', slug: 'router-tp-link-archer-c6',
    name: 'Router TP-Link AC1200 Archer C6', brand: 'TP-Link', model: 'Archer C6',
    category: 'redes', subcategory: 'routers', image: 'router',
    price: 149, stock: 22, rating: 4.7, reviews: 75, offer: false,
    shortDesc: 'Router WiFi de doble banda AC1200 con 4 antenas y tecnología MU-MIMO.',
    longDesc: 'El TP-Link Archer C6 ofrece WiFi de doble banda AC1200 con velocidades combinadas de hasta 1200 Mbps. Sus 4 antenas externas y la tecnología MU-MIMO con Beamforming aseguran una cobertura estable y simultánea para todos tus dispositivos, ideal para hogares y oficinas pequeñas.',
    specs: { 'Velocidad': 'AC1200 (300+867 Mbps)', Bandas: 'Doble banda 2.4/5 GHz', Antenas: '4 externas', Puertos: '4x LAN Gigabit', Garantía: '1 año' },
    compatibilities: [], related: [11, 6, 2],
  },
  {
    id: 6, sku: 'LOG-H390', slug: 'audifonos-logitech-h390',
    name: 'Audífonos Logitech H390 USB', brand: 'Logitech', model: 'H390',
    category: 'accesorios', subcategory: 'audifonos', image: 'headset',
    price: 89, stock: 30, rating: 4.6, reviews: 62, offer: false,
    shortDesc: 'Audífonos USB Logitech H390 con micrófono con cancelación de ruido.',
    longDesc: 'Los audífonos Logitech H390 con conexión USB ofrecen sonido digital envolvente y un micrófono con cancelación de ruido ideal para videollamadas. Sus almohadillas acolchadas y diadema ajustable brindan comodidad durante largas jornadas de trabajo.',
    specs: { Conexión: 'USB', Micrófono: 'Con cancelación de ruido', Controles: 'En línea (volumen/mute)', Garantía: '2 años' },
    compatibilities: [], related: [1, 5, 11],
  },
  {
    id: 7, sku: 'HP-VICTUS15', slug: 'laptop-hp-victus-15',
    name: 'Laptop HP Victus 15 Gaming', brand: 'HP', model: 'Victus 15',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 3499, oldPrice: 3899, stock: 5, rating: 4.8, reviews: 41, offer: true,
    shortDesc: 'Laptop gamer HP Victus 15 con Ryzen 5, RTX 3050 y 16GB RAM.',
    longDesc: 'La HP Victus 15 está pensada para gaming y creación de contenido. Con procesador AMD Ryzen 5, tarjeta gráfica NVIDIA RTX 3050, 16GB de RAM y pantalla de 144Hz, ejecuta los títulos más exigentes con fluidez.',
    specs: { Procesador: 'AMD Ryzen 5 5600H', RAM: '16GB DDR4', Gráficos: 'NVIDIA RTX 3050 4GB', Pantalla: '15.6" FHD 144Hz', Garantía: '1 año' },
    compatibilities: [], related: [1, 6, 5],
  },
  {
    id: 8, sku: 'BR-TN660', slug: 'toner-brother-tn660',
    name: 'Tóner Brother TN-660 Negro Original', brand: 'Brother', model: 'TN-660',
    category: 'toner', subcategory: 'toner-brother', image: 'toner',
    price: 119, stock: 18, rating: 4.7, reviews: 53, offer: false,
    shortDesc: 'Tóner Brother TN-660 de alto rendimiento, ~2600 páginas.',
    longDesc: 'El tóner original Brother TN-660 de alto rendimiento entrega aproximadamente 2600 páginas con texto nítido y profesional, optimizando el costo por impresión en tus equipos Brother.',
    specs: { Color: 'Negro', Rendimiento: '~2600 páginas', Tipo: 'Original alto rendimiento', Garantía: '1 año' },
    compatibilities: ['Brother HL-L2300D', 'Brother DCP-L2540DW', 'Brother MFC-L2700DW'], related: [3, 2, 4],
  },
  {
    id: 9, sku: 'CN-GI190', slug: 'tinta-canon-gi-190',
    name: 'Tinta Canon GI-190 Negro Original', brand: 'Canon', model: 'GI-190',
    category: 'tintas', subcategory: 'tinta-canon', image: 'ink',
    price: 45, stock: 35, rating: 4.6, reviews: 38, offer: false,
    shortDesc: 'Botella de tinta Canon GI-190 negro original para impresoras MegaTank.',
    longDesc: 'La tinta Canon GI-190 negra original ofrece impresiones de alta calidad y bajo costo por página para tus impresoras Canon PIXMA G-series MegaTank.',
    specs: { Color: 'Negro', Contenido: '135 ml', Tipo: 'Original', Garantía: '6 meses' },
    compatibilities: ['Canon G1110', 'Canon G2110', 'Canon G3110'], related: [4, 2, 8],
  },
  {
    id: 10, sku: 'SAM-T350', slug: 'monitor-samsung-t350',
    name: 'Monitor Samsung 24" T350 Full HD', brand: 'Samsung', model: 'T350',
    category: 'laptops-pc', subcategory: 'monitores', image: 'laptop',
    price: 549, stock: 12, rating: 4.7, reviews: 67, offer: false,
    shortDesc: 'Monitor Samsung 24" Full HD IPS, 75Hz, FreeSync.',
    longDesc: 'Monitor Samsung T350 de 24" con panel IPS Full HD, tasa de refresco de 75Hz y tecnología AMD FreeSync para imágenes fluidas. Diseño sin bordes en 3 lados, ideal para multitarea.',
    specs: { Tamaño: '24"', Resolución: '1920x1080 Full HD', Panel: 'IPS', Frecuencia: '75Hz', Garantía: '2 años' },
    compatibilities: [], related: [1, 7, 6],
  },
  {
    id: 11, sku: 'TPL-TLSG108', slug: 'switch-tp-link-sg108',
    name: 'Switch TP-Link TL-SG108 8 Puertos Gigabit', brand: 'TP-Link', model: 'TL-SG108',
    category: 'redes', subcategory: 'switches', image: 'router',
    price: 99, stock: 26, rating: 4.8, reviews: 89, offer: false,
    shortDesc: 'Switch no administrable de 8 puertos Gigabit, carcasa metálica.',
    longDesc: 'El TP-Link TL-SG108 amplía tu red con 8 puertos Gigabit plug-and-play. Su carcasa metálica robusta y el funcionamiento silencioso lo hacen ideal para hogares y oficinas.',
    specs: { Puertos: '8x Gigabit', Tipo: 'No administrable', Carcasa: 'Metálica', Garantía: '3 años' },
    compatibilities: [], related: [5, 6, 1],
  },
  {
    id: 12, sku: 'HP-M404DN', slug: 'impresora-hp-laserjet-m404dn',
    name: 'Impresora HP LaserJet Pro M404dn', brand: 'HP', model: 'M404dn',
    category: 'impresoras', subcategory: 'laser', image: 'printer',
    price: 1099, oldPrice: 1299, stock: 9, rating: 4.8, reviews: 44, offer: true,
    shortDesc: 'Impresora láser monocromática HP LaserJet Pro M404dn con dúplex y red.',
    longDesc: 'La HP LaserJet Pro M404dn es una impresora láser monocromática de alto rendimiento para entornos de trabajo exigentes. Imprime hasta 38 ppm, incluye impresión a doble cara automática y conexión Ethernet.',
    specs: { Tipo: 'Láser monocromática', 'Velocidad': '38 ppm', Dúplex: 'Automático', Conectividad: 'USB, Ethernet', Garantía: '1 año' },
    compatibilities: ['Tóner HP 58A', 'Tóner HP 59A'], related: [3, 2, 8],
  },
  {
    id: 13, sku: 'LEN-LEGION5', slug: 'laptop-lenovo-legion-5-15ach6h',
    name: 'Lenovo Legion 5 15ACH6H', brand: 'Lenovo', model: 'Legion 5 15ACH6H',
    category: 'laptops-pc', subcategory: 'laptops-gamer', image: 'laptop',
    price: 3299, oldPrice: 3799, off: 12, stock: 10, rating: 4.6, reviews: 98, offer: true,
    subtitle: 'Ryzen 5 5600H | 16GB | 512GB SSD',
    blurb: 'AMD Ryzen 5 5600H · 16GB RAM · 512GB SSD · GTX 1650 · 15.6" FHD · Windows 11',
    trendTag: '#Gaming', rankLabel: '#1 Más vendidos en Laptops Gamer',
    shortDesc: 'Laptop gamer Lenovo Legion 5 con Ryzen 5 5600H, GTX 1650 y 16GB RAM.',
    longDesc: 'La Lenovo Legion 5 ofrece potencia gamer con procesador AMD Ryzen 5 5600H, gráficos NVIDIA GTX 1650 y 16GB de RAM, con un sistema de refrigeración avanzado para largas sesiones.',
    highlights: ['Gráficos dedicados GTX 1650', 'Refrigeración Legion ColdFront', 'Teclado retroiluminado'],
    specs: { Procesador: 'AMD Ryzen 5 5600H', 'Memoria RAM': '16GB DDR4', Almacenamiento: '512GB SSD', Gráficos: 'NVIDIA GTX 1650 4GB', Pantalla: '15.6" FHD 120Hz', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 14, 15],
  },
  {
    id: 14, sku: 'ASUS-X1502ZA', slug: 'laptop-asus-vivobook-15-x1502za',
    name: 'ASUS Vivobook 15 X1502ZA', brand: 'ASUS', model: 'Vivobook 15 X1502ZA',
    category: 'laptops-pc', subcategory: 'ultrabooks', image: 'laptop',
    price: 2299, oldPrice: 3749, off: 39, stock: 9, rating: 4.5, reviews: 56, offer: true, flag: 'oferta',
    subtitle: 'i7 | 16GB | 512GB SSD',
    blurb: 'Intel Core i7 · 16GB RAM · 512GB SSD · 15.6" FHD · Windows 11',
    trendTag: '#Ultrabook', rankLabel: '#1 Más vendidos en Ultrabooks',
    shortDesc: 'Ultrabook ASUS Vivobook 15 con Intel Core i7, 16GB RAM y 512GB SSD.',
    longDesc: 'La ASUS Vivobook 15 X1502ZA combina un procesador Intel Core i7, 16GB de RAM y diseño delgado, ideal para productividad y entretenimiento.',
    highlights: ['Procesador Intel Core i7', 'Pantalla NanoEdge 15.6"', 'Diseño liviano'],
    specs: { Procesador: 'Intel Core i7-1255U', 'Memoria RAM': '16GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" FHD', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 13, 15],
  },
  {
    id: 15, sku: 'ACER-A515-57', slug: 'laptop-acer-aspire-5-a515-57',
    name: 'Acer Aspire 5 A515-57', brand: 'Acer', model: 'Aspire 5 A515-57',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 1999, stock: 14, rating: 4.5, reviews: 34, offer: false, flag: 'nuevo',
    subtitle: 'i5 | 8GB | 512GB SSD',
    blurb: 'Intel Core i5 · 8GB RAM · 512GB SSD · 15.6" FHD · Windows 11',
    trendTag: '#Nuevos', rankLabel: '#1 Más vendidos en Acer',
    shortDesc: 'Laptop Acer Aspire 5 con Intel Core i5, 8GB RAM y 512GB SSD.',
    longDesc: 'La Acer Aspire 5 A515-57 ofrece un equilibrio entre rendimiento y portabilidad con Intel Core i5 y pantalla Full HD, ideal para el día a día.',
    highlights: ['Pantalla Full HD', 'Diseño delgado de metal', 'Wi-Fi 6'],
    specs: { Procesador: 'Intel Core i5-1235U', 'Memoria RAM': '8GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" FHD', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 13, 14],
  },
  {
    id: 16, sku: 'LEN-V15G4', slug: 'laptop-lenovo-v15-g4',
    name: 'Laptop Lenovo V15 G4', brand: 'Lenovo', model: 'V15 G4',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 1599, oldPrice: 1899, off: 16, stock: 16, rating: 4.7, reviews: 98, offer: true,
    subtitle: '15.6" FHD | 8GB | 512GB SSD',
    blurb: 'Intel Core i5 · 8GB RAM · 512GB SSD · 15.6" FHD',
    trendTag: '#Laptops', rankLabel: '#1 Más vendidos en Lenovo',
    shortDesc: 'Laptop Lenovo V15 G4 con Intel Core i5, 8GB RAM y 512GB SSD.',
    longDesc: 'La Lenovo V15 G4 es una laptop confiable para trabajo y estudio, con pantalla Full HD y almacenamiento SSD rápido.',
    highlights: ['Pantalla Full HD', 'Almacenamiento SSD', 'Ligera y resistente'],
    specs: { Procesador: 'Intel Core i5-1235U', 'Memoria RAM': '8GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" FHD', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 17, 18],
  },
  {
    id: 17, sku: 'ASUS-VB15', slug: 'laptop-asus-vivobook-15',
    name: 'Laptop ASUS Vivobook 15', brand: 'ASUS', model: 'Vivobook 15',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 2090, oldPrice: 2390, off: 12, stock: 11, rating: 4.8, reviews: 76, offer: true,
    subtitle: 'i5 1235U | 8GB | 512GB SSD',
    blurb: 'Intel Core i5 1235U · 8GB RAM · 512GB SSD · 15.6" FHD',
    trendTag: '#Laptops', rankLabel: '#1 Más vendidos en ASUS',
    shortDesc: 'Laptop ASUS Vivobook 15 con Intel Core i5, 8GB RAM y 512GB SSD.',
    longDesc: 'La ASUS Vivobook 15 ofrece diseño delgado y rendimiento equilibrado para la productividad diaria.',
    highlights: ['Diseño NanoEdge', 'SSD veloz', 'Wi-Fi 6'],
    specs: { Procesador: 'Intel Core i5-1235U', 'Memoria RAM': '8GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" FHD', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 16, 18],
  },
  {
    id: 18, sku: 'HP-255G9', slug: 'laptop-hp-255-g9',
    name: 'Laptop HP 255 G9', brand: 'HP', model: '255 G9',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 1799, oldPrice: 2090, off: 15, stock: 13, rating: 4.7, reviews: 62, offer: true,
    subtitle: 'Ryzen 5 5625U | 8GB | 512GB',
    blurb: 'AMD Ryzen 5 5625U · 8GB RAM · 512GB SSD · 15.6" FHD',
    trendTag: '#Laptops', rankLabel: '#1 Más vendidos en HP',
    shortDesc: 'Laptop HP 255 G9 con AMD Ryzen 5, 8GB RAM y 512GB SSD.',
    longDesc: 'La HP 255 G9 con procesador AMD Ryzen 5 ofrece rendimiento fluido para tareas diarias y multitarea.',
    highlights: ['Procesador Ryzen 5', 'Almacenamiento SSD', 'Pantalla Full HD'],
    specs: { Procesador: 'AMD Ryzen 5 5625U', 'Memoria RAM': '8GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" FHD', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 16, 17],
  },
  {
    id: 19, sku: 'ACER-A3', slug: 'laptop-acer-aspire-3',
    name: 'Laptop Acer Aspire 3', brand: 'Acer', model: 'Aspire 3',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 1699, oldPrice: 1899, off: 10, stock: 15, rating: 4.6, reviews: 54, offer: true,
    subtitle: 'Ryzen 5 | 8GB | 512GB SSD',
    blurb: 'AMD Ryzen 5 · 8GB RAM · 512GB SSD · 15.6" FHD',
    trendTag: '#Laptops', rankLabel: '#1 Más vendidos en Acer',
    shortDesc: 'Laptop Acer Aspire 3 con AMD Ryzen 5, 8GB RAM y 512GB SSD.',
    longDesc: 'La Acer Aspire 3 es una laptop accesible y confiable para el día a día, con SSD y pantalla Full HD.',
    highlights: ['Buen rendimiento', 'SSD rápido', 'Ligera'],
    specs: { Procesador: 'AMD Ryzen 5', 'Memoria RAM': '8GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" FHD', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 18, 20],
  },
  {
    id: 20, sku: 'DELL-INSP15', slug: 'laptop-dell-inspiron-15',
    name: 'Laptop Dell Inspiron 15', brand: 'Dell', model: 'Inspiron 15',
    category: 'laptops-pc', subcategory: 'laptops', image: 'laptop',
    price: 2149, oldPrice: 2590, off: 17, stock: 12, rating: 4.8, reviews: 81, offer: true,
    subtitle: 'i5 1235U | 8GB | 512GB SSD',
    blurb: 'Intel Core i5 1235U · 8GB RAM · 512GB SSD · 15.6" FHD',
    trendTag: '#Laptops', rankLabel: '#1 Más vendidos en Dell',
    shortDesc: 'Laptop Dell Inspiron 15 con Intel Core i5, 8GB RAM y 512GB SSD.',
    longDesc: 'La Dell Inspiron 15 combina diseño moderno y rendimiento confiable para trabajo y estudio.',
    highlights: ['Diseño moderno', 'SSD veloz', 'Pantalla Full HD'],
    specs: { Procesador: 'Intel Core i5-1235U', 'Memoria RAM': '8GB DDR4', Almacenamiento: '512GB SSD', Pantalla: '15.6" FHD', 'Sistema Operativo': 'Windows 11', Garantía: '1 año' },
    compatibilities: [], related: [1, 19, 16],
  },
]

// Metadatos por categoría para la página de listado (encabezado, subcategorías
// con conteos, marcas con conteos y rango de precio del mockup).
export const categoryMeta = {
  'laptops-pc': {
    title: 'Laptops',
    subtitle: 'Encuentra las mejores laptops para trabajo, estudio y entretenimiento.',
    crumb: [{ label: 'Laptops & PC', to: '/categoria/laptops-pc' }, { label: 'Laptops' }],
    subcats: [
      { name: 'Laptops', slug: '', count: 96 },
      { name: 'Laptops Gamer', slug: 'laptops-gamer', count: 24 },
      { name: 'Ultrabooks', slug: 'ultrabooks', count: 18 },
      { name: '2 en 1 / Convertibles', slug: 'convertibles', count: 14 },
      { name: 'Accesorios para Laptop', slug: 'monitores', count: 32 },
    ],
    brandCounts: [['HP', 28], ['Lenovo', 22], ['Dell', 18], ['ASUS', 15], ['Acer', 13]],
    price: [699, 6999],
    featured: [1, 13, 14, 15, 18, 20, 17, 19, 16, 7],
  },
}

export const getCategoryMeta = (slug) => categoryMeta[slug] || null

export const getProduct = (slug) => products.find((p) => p.slug === slug)
export const getCategory = (slug) => categories.find((c) => c.slug === slug)
export const byCategory = (catSlug) => products.filter((p) => p.category === catSlug)

export const peso = (n) =>
  'S/ ' + n.toLocaleString('es-PE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
